# Generated by Django 3.1.7 on 2021-03-04 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('sum', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Сумма')),
                ('comment', models.CharField(blank=True, max_length=200, verbose_name='Комментарий')),
                ('type_transfer', models.CharField(blank=True, choices=[('+', 'Приход'), ('-', 'Расход')], default='+', help_text='Тип движения денег', max_length=1, verbose_name='Тип движения')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='transfers.categorytransfer', verbose_name='Категория')),
            ],
        ),
    ]
