# Generated by Django 3.1.7 on 2021-03-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='type_transfer',
            field=models.CharField(blank=True, choices=[('+', 'Приход'), ('-', 'Расход')], default=('-', 'Расход'), max_length=1, verbose_name='Тип движения'),
        ),
    ]
